sudo: false
dist: trusty
language: node_js
node_js:
- "8"

cache:
  yarn: true
  directories:
     - ./node_modules

script:
  - echo build fti portal styles and styleguide based on patternlab ...
  - npm run build

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key:
      secure: $NPM_TOURSTREAM_EU_TOKEN
    on:
      node: "8"
      tags: true
      repo: tourstream/fti-portal-styleguide
  - provider: gcs
    skip_cleanup: true
    detect_encoding: true
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_ACCESS_SECRET
    bucket: $GCS_BUCKET
    acl: public-read
    local-dir: dist-master
    on:
      node: "8"
      branch: master
      repo: tourstream/fti-portal-styleguide
  - provider: gcs
    skip_cleanup: true
    detect_encoding: true
    access_key_id: $GCS_ACCESS_KEY_ID
    secret_access_key: $GCS_ACCESS_SECRET
    bucket: $GCS_BUCKET
    acl: public-read
    local-dir: dist-version
    on:
      node: "8"
      tags: true
      repo: tourstream/fti-portal-styleguide
